version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jornada-app
    container_name: jornada-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=jornada
      - DB_USERNAME=root
      - DB_PASSWORD=guitar123
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    container_name: jornada-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
